# # backend/app/seed.py
# def seed_database():
#     if poles_table_is_empty():
#         load_csv_into_db("data/pole_registry.csv")
#         load_csv_into_db("data/dt_registry.csv")
"""
backend/app/seed.py

Loads data/pole_registry.csv and data/dt_registry.csv into Postgres on
startup, ONLY if the tables are currently empty. This is what satisfies
G3 in 03-deliverables-and-submission.md: the reviewer must see a working,
populated system immediately after `docker compose up`, not a blank map.

Called from main.py's FastAPI startup event -- see the bottom of this file
for how that wiring looks.

Data files are pre-generated by simulator/generate_grid.py and committed
to the repo (see DECISIONS.md for why we don't regenerate on every boot:
faster startup, deterministic via random.seed(42)).
"""

import csv
import os

from sqlalchemy.orm import Session

from app.database import SessionLocal, engine, Base
from app.models import Pole, Transformer

# Path to CSVs relative to the container's working directory. Must match
# wherever the Dockerfile COPYs data/ into the image -- verify this once
# Phase 6 (deployment) is underway.
DATA_DIR = os.getenv("DATA_DIR", "data")


def _load_dt_registry(db: Session) -> int:
    path = os.path.join(DATA_DIR, "dt_registry.csv")
    count = 0
    with open(path, newline="") as f:
        for row in csv.DictReader(f):
            db.add(Transformer(
                dt_id=row["dt_id"],
                feeder_id=row["feeder_id"],
                lat=float(row["lat"]),
                lon=float(row["lon"]),
                capacity_kva=float(row["capacity_kva"]) if row["capacity_kva"] else None,
                households_served=int(row["households_served"]) if row["households_served"] else None,
            ))
            count += 1
    db.commit()
    return count


def _load_pole_registry(db: Session) -> int:
    path = os.path.join(DATA_DIR, "pole_registry.csv")
    count = 0
    with open(path, newline="") as f:
        for row in csv.DictReader(f):
            db.add(Pole(
                pole_id=row["pole_id"],
                lat=float(row["lat"]),
                lon=float(row["lon"]),
                feeder_id=row["feeder_id"],
                dt_id=row["dt_id"],
                seq_on_line=int(row["seq_on_line"]) if row["seq_on_line"] else None,
                parent_pole_id=row["parent_pole_id"] or None,
                pole_type=row["pole_type"] or None,
                ward=row["ward"] or None,
                pincode=row["pincode"] or None,
                device_id=row["device_id"] or None,
            ))
            count += 1
    db.commit()
    return count


def seed_database():
    """
    Idempotent: safe to call on every startup. Only actually loads data
    the first time (when the poles table is empty).
    """
    Base.metadata.create_all(bind=engine)  # creates tables if they don't exist

    db = SessionLocal()
    try:
        existing = db.query(Pole).first()
        if existing is not None:
            print("seed_database: poles table already populated, skipping.")
            return

        n_dts = _load_dt_registry(db)
        n_poles = _load_pole_registry(db)
        print(f"seed_database: loaded {n_dts} transformers and {n_poles} poles.")
    finally:
        db.close()


if __name__ == "__main__":
    # Manual run for testing: `python -m app.seed` from backend/
    seed_database()